name: bsanders
favicon: null
layout_spectrum: 0.2929426447954029
typography_spectrum: 0.846138097345829
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8111775149591267
  lightness: 0.6726840327028185
  saturation: 0.7105702057015151
  rhythmicContrast: 0.5102881514467299
purpose: []
