name: bsanders
favicon: null
layout_spectrum: 0.2929426447954029
typography_spectrum: 0.846138097345829
title: Bernie Sanders 2016 - Unofficial
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5573b1'
    - '#820b0c'
    - '#d7d7e3'
    - '#dc2225'
    - '#080d2d'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
